name: Deploy
on:
  release:
    types: [created]

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: "Set Version"
      shell: bash
      run: |
        APP_VERSION=${GITHUB_REF##*/}
        APP_VERSION="${APP_VERSION:1}"
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "APP_VERSION=\"$APP_VERSION\"" > src/version.py
        file=app/share/metainfo/releases/io.github.junalmeida.webapps_manager.releases.xml
        content="\t<release version=\"$APP_VERSION\" date=\"$(date +%Y-%m-%d)\"/>" 
        echo $content
        C=$(echo $content | sed 's/\//\\\//g')
        sed "/<\/releases>/ s/.*/${C}\n&/" $file > $file.tmp
        mv $file.tmp $file
    - uses: flatpak/flatpak-github-actions/flatpak-builder@master
      name: "Build"
      with:
        upload-artifact: false
        bundle: io.github.junalmeida.webapps_manager.flatpak
        manifest-path: io.github.junalmeida.webapps_manager.json
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          **/io.github.junalmeida.webapps_manager.flatpak
    # - uses: flatpak/flatpak-github-actions/flat-manager@v6
    #   name: "Deploy"
    #   with:
    #     repository: flathub
    #     flat-manager-url: https://flatpak-api.elementary.io
    #     token: some_very_hidden_token
